# Generated by Django 3.2.16 on 2022-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
